# This is to mimic the OpenShift behaviour of adding the dynamic user to group 0.
RUN usermod -G 0 $USERNAME
ENV HOME /home/${USERNAME}
WORKDIR /home/${USERNAME}

RUN chmod g+w /etc/passwd && \
    touch /etc/sub{g,u}id && \
    chmod -v ug+rw /etc/sub{g,u}id && \
    echo -e "runner:1:999\nrunner:1001:64535" > /etc/subuid && \
    echo -e "runner:1:999\nrunner:1001:64535" > /etc/subgid

COPY --chown=${USERNAME}:0 entrypoint.sh uid.sh register.sh get_github_app_token.sh ./

ADD containers.conf /etc/containers/containers.conf
ADD podman-containers.conf /home/runner/.config/containers/containers.conf

RUN mkdir -p /home/runner/.local/share/containers && \
    chown runner:runner -R /home/runner && \
    chmod 644 /etc/containers/containers.conf

ADD storage.conf /usr/share/containers/storage.conf
RUN sed -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /usr/share/containers/storage.conf \
           > /etc/containers/storage.conf

RUN printf '/run/secrets/etc-pki-entitlement:/run/secrets/etc-pki-entitlement\n/run/secrets/rhsm:/run/secrets/rhsm\n' > /etc/containers/mounts.conf

VOLUME /var/lib/containers
VOLUME /home/runner/.local/share/containers

RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

ENV _CONTAINERS_USERNS_CONFIGURED=""

COPY --chown=${USERNAME}:0 get-runner-release.sh ./
RUN chmod ug+x ./get-runner-release.sh
RUN ./get-runner-release.sh
RUN ./bin/installdependencies.sh
RUN pip install --progress-bar off 'molecule>=24.2.0' 'molecule-plugins[docker]>=23.0.0' 'molecule-plugins[podman]' "ansible-core~=${ANSIBLE_VERSION}"

ENTRYPOINT ./entrypoint.sh

